# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_rename_classified_failure_to_classification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FailureClassification',
            new_name='FailureType',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='failure_classification',
            new_name='failure_type',
        ),
        migrations.RenameField(
            model_name='jobnote',
            old_name='failure_classification',
            new_name='failure_type',
        ),
    ]
